# This is a basic workflow to help you get started with Actions

name: CI-diff

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: sudo apt install -y libgmp-dev libmpc-dev git build-essential fakeroot libncurses5-dev libssl-dev ccache dfu-util u-boot-tools device-tree-compiler mtools bc python3 cpio zip unzip rsync file wget flex bison language-pack-en libtinfo5 x11-utils xvfb dbus-x11 libswt-glx-gtk-4-jni libgtk2.0-0

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        env:
          SKIP_LEGAL: 1
        run: |
          set -e -x
          # Clone original v0.38 firware for PlutoSDR
          git clone --depth 1 --branch v0.38 --recursive https://github.com/analogdevicesinc/plutosdr-fw.git plutosdr-fw_0.38_libre
          # Apply patch for LibreSDR
          ./apply.sh

      - name: Run a multi-line script
        env:
          SKIP_LEGAL: 1
        run: |
          set -e -x
          cd plutosdr-fw_0.38_libre
          git diff --no-index buildroot/board/libre buildroot/board/pluto || true

      - name: Run a multi-line script
        env:
          SKIP_LEGAL: 1
        run: |
          set -e -x
          cd plutosdr-fw_0.38_libre
          git diff --no-index hdl/projects/libre hdl/projects/pluto || true

      - name: Run a multi-line script
        env:
          SKIP_LEGAL: 1
        run: |
          set -e -x
          cd plutosdr-fw_0.38_libre
          git diff --no-index linux/arch/arm/boot/dts/zynq-libre.dtsi linux/arch/arm/boot/dts/zynq-pluto-sdr.dtsi || true
          git diff --no-index linux/arch/arm/configs/zynq_libre_defconfig linux/arch/arm/configs/zynq_pluto_defconfig || true
         
      - name: Run a multi-line script
        env:
          SKIP_LEGAL: 1
        run: |
          set -e -x
          cd plutosdr-fw_0.38_libre
          git diff --no-index uboot/configs/zynq_libre_defconfig u-boot-xlnx/configs/zynq_pluto_defconfig || true
          git diff --no-index uboot/arch/arm/dts/zynq-libre-sdr.dts u-boot-xlnx/arch/arm/dts/zynq-pluto-sdr.dts || true
